### ISSUE TITLE
Problems with app on play store

### ISSUE THREAD

**Issue by pablopasten** [tananaev/passport-reader#2]
Hi friend 
i write from Chile. I have been woriking with your project to try to read the card id but when i call the app , crachit instantily. ( im using app from play store)
This is the error i read on logcat:
```
05-15 14:26:31.071: E/AndroidRuntime(14483): Process: com.tananaev.passportreader, PID: 14483
05-15 14:26:31.071: E/AndroidRuntime(14483): java.lang.NoClassDefFoundError: org.spongycastle.util.Arrays
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.asn1.ASN1ObjectIdentifier$OidHandle.<init>(ASN1ObjectIdentifier.java:449)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.asn1.ASN1ObjectIdentifier.intern(ASN1ObjectIdentifier.java:425)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.asn1.pkcs.PKCSObjectIdentifiers.<clinit>(PKCSObjectIdentifiers.java:117)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jcajce.provider.digest.MD2$Mappings.configure(MD2.java:70)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(BouncyCastleProvider.java:220)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jce.provider.BouncyCastleProvider.setup(BouncyCastleProvider.java:135)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jce.provider.BouncyCastleProvider.access$000(BouncyCastleProvider.java:44)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jce.provider.BouncyCastleProvider$1.run(BouncyCastleProvider.java:127)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at java.security.AccessController.doPrivileged(AccessController.java:45)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at org.spongycastle.jce.provider.BouncyCastleProvider.<init>(BouncyCastleProvider.java:123)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at com.tananaev.passportreader.MainActivity.<clinit>(MainActivity.java:73)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at java.lang.Class.newInstanceImpl(Native Method)
05-15 14:26:31.071: E/AndroidRuntime(14483): 	at java.lang.Class.newInstance(Class.java:1208)
```

Im useing a sony Z8

**Comment by tananaev** [comment]
Are you able to compile the project? You can try different version of Spongy Castle library.

**Comment by pablopasten** [comment]
Yes, I downloaded the source and compile, had other errors related to the views, but I could not replicate that I mentioned in the previous comment.

**Comment by tananaev** [comment]
Not sure why it's happening. It looks like some class is missing in the library.

**Comment by tananaev** [comment]
I've added a catch for the exception. I hope it works now.
