### ISSUE TITLE
German passport works partially

### ISSUE THREAD

**Issue by fds2610** [tananaev/passport-reader#58]
All data incl photo was retrieved successful, though passive authentication and the chip authentication failed.

I wonder if there is no biometric data stores in the passport.

NB: i tested with german passport and NOT with german ID card called "Personalausweis".

Version: 
Android 13, LineageOS 20
E-Passport Reader 3.7.1

**Comment by cirosantilli** [comment]
Related: https://github.com/tananaev/passport-reader/issues/54

**Comment by DerMEnscHMarkO** [comment]
Hello there, so what schould i say? My German Personalausweis is not working.?

**Comment by kaduvert** [comment]
@tananaev

<details>
  <summary>german passport logcat (one scan)</summary>

```
498.435 10260 16075 16075 D InsetsController: hide(ime(), fromIme=false)
498.435 10260 16075 16075 I ImeTracker: com.tananaev.passportreader:f16c7fe2: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
498.625 10260 16075 16163 D ProfileInstaller: Installing profile for com.tananaev.passportreader
500.741 10260 16075 16100 W MainActivity: org.jmrtd.PACEException: PICC side exception in tranceiving nonce step (SW = 0x6982: SECURITY STATUS NOT SATISFIED)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.PACEProtocol.doPACEStep1(PACEProtocol.java:382)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.PACEProtocol.doPACE(PACEProtocol.java:254)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.PACEProtocol.doPACE(PACEProtocol.java:180)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.PassportService.doPACE(PassportService.java:406)
500.741 10260 16075 16100 W MainActivity: 	at com.tananaev.passportreader.MainActivity$ReadTask.doInBackground(MainActivity.kt:254)
500.741 10260 16075 16100 W MainActivity: 	at com.tananaev.passportreader.MainActivity$ReadTask.doInBackground(MainActivity.kt:222)
500.741 10260 16075 16100 W MainActivity: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
500.741 10260 16075 16100 W MainActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
500.741 10260 16075 16100 W MainActivity: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
500.741 10260 16075 16100 W MainActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
500.741 10260 16075 16100 W MainActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
500.741 10260 16075 16100 W MainActivity: 	at java.lang.Thread.run(Thread.java:1119)
500.741 10260 16075 16100 W MainActivity: Caused by: org.jmrtd.AccessDeniedException: Sending general authenticate failed (SW = 0x6982: SECURITY STATUS NOT SATISFIED)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.PACEAPDUSender.sendGeneralAuthenticate(PACEAPDUSender.java:177)
500.741 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.PACEProtocol.doPACEStep1(PACEProtocol.java:371)
500.741 10260 16075 16100 W MainActivity: 	... 11 more
501.373 10260 16075 16075 D VRI[RegularActivity]: visibilityChanged oldVisibility=true newVisibility=false
503.349 10260 16075 16083 I .passportreader: Background concurrent copying GC freed 37MB AllocSpace bytes, 5(100KB) LOS objects, 84% free, 4522KB/28MB, paused 121us,37us total 149.954ms
504.169 10260 16075 16075 D ViewRootImpl: Skipping stats log for color mode
504.240 10260 16075 16075 D InsetsController: hide(ime(), fromIme=false)
504.240 10260 16075 16075 I ImeTracker: com.tananaev.passportreader:15ac1d15: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
507.686 10260 16075 16100 W MainActivity: net.sf.scuba.smartcards.CardServiceException: Sending MSE AT failed (SW = 0x6A80: WRONG DATA or FILEHEADER INCONSISTENT)
507.686 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.EACCAAPDUSender.sendMSESetATIntAuth(EACCAAPDUSender.java:131)
507.686 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.EACCAProtocol.sendPublicKey(EACCAProtocol.java:184)
507.686 10260 16075 16100 W MainActivity: 	at org.jmrtd.protocol.EACCAProtocol.doCA(EACCAProtocol.java:146)
507.686 10260 16075 16100 W MainActivity: 	at org.jmrtd.PassportService.doEACCA(PassportService.java:428)
507.686 10260 16075 16100 W MainActivity: 	at com.tananaev.passportreader.MainActivity$ReadTask.doChipAuth(MainActivity.kt:313)
507.686 10260 16075 16100 W MainActivity: 	at com.tananaev.passportreader.MainActivity$ReadTask.doInBackground(MainActivity.kt:281)
507.686 10260 16075 16100 W MainActivity: 	at com.tananaev.passportreader.MainActivity$ReadTask.doInBackground(MainActivity.kt:222)
507.686 10260 16075 16100 W MainActivity: 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
507.686 10260 16075 16100 W MainActivity: 	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
507.686 10260 16075 16100 W MainActivity: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
507.686 10260 16075 16100 W MainActivity: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
507.686 10260 16075 16100 W MainActivity: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
507.686 10260 16075 16100 W MainActivity: 	at java.lang.Thread.run(Thread.java:1119)
508.329 10260 16075 16083 I .passportreader: Background young concurrent copying GC freed 18MB AllocSpace bytes, 18(360KB) LOS objects, 49% free, 14MB/28MB, paused 98us,40us total 119.906ms
508.640 10260 16075 16083 I .passportreader: Background concurrent copying GC freed 24MB AllocSpace bytes, 0(0B) LOS objects, 66% free, 15MB/46MB, paused 153us,98us total 138.110ms
508.697 10260 16075 16075 I .passportreader: AssetManager2(0x754003a8f8) locale list changing from [] to [de-DE]
508.706 10260 16075 16075 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
508.723 10260 16075 16099 E perf_hint: createSessionUsingConfig: PerformanceHint cannot create session. PowerHAL is not supported!
508.930 10260 16075 16075 D InsetsController: hide(ime(), fromIme=false)
508.930 10260 16075 16075 I ImeTracker: com.tananaev.passportreader:68092c3f: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
509.288 10260 16075 16075 D VRI[RegularActivity]: visibilityChanged oldVisibility=true newVisibility=false
510.776 10260 16075 16075 D VRI[ResultActivity]: visibilityChanged oldVisibility=true newVisibility=false
```
</details>

Displays Name, First Name, DOB and such but both cryptographic checks fail.

Let me know if you need more information
